#!/usr/bin/env python3
"""Generate a single self-contained SQL file for the Supabase SQL Editor.

Produces DROP SCHEMA -> CREATE SCHEMA -> DDL -> INSERTs, so the whole
database can be built by pasting one file into the web console. This exists
because running the Python importer requires local network access to the
database, which is not always convenient.

Usage:
    python scripts/generate_seed_sql.py \
        --file ../output/telugu_movies_2000_2023.csv \
        --out ../supabase_setup.sql
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
from pathlib import Path
from typing import Any, Iterator

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app.services.daily_movie import is_eligible, quality_score  # noqa: E402
from app.services.movie_service import normalize_title  # noqa: E402

# Rows per INSERT statement. Large enough to keep the file compact, small
# enough that the SQL Editor does not choke on a single statement.
BATCH = 200


def quote(value: str | None) -> str:
    """SQL string literal with quotes doubled.

    Titles legitimately contain apostrophes ("Ileana D'Cruz"), so escaping
    is mandatory rather than cosmetic.
    """
    if value is None or value == "":
        return "NULL"
    return "'" + str(value).replace("'", "''") + "'"


def split_values(value: Any) -> list[str]:
    """Normalise a multi-value field from CSV (pipes) or JSON (arrays)."""
    if value is None:
        return []
    items = (
        [str(item).strip() for item in value]
        if isinstance(value, list)
        else [part.strip() for part in str(value).split("|")]
    )
    seen: set[str] = set()
    out: list[str] = []
    for item in items:
        if not item:
            continue
        key = item.casefold()
        if key in seen:
            continue
        seen.add(key)
        out.append(item)
    return out


def join_values(values: list[str]) -> str | None:
    return "|".join(values) if values else None


def read_rows(path: Path) -> Iterator[dict[str, Any]]:
    if path.suffix.lower() == ".json":
        payload = json.loads(path.read_text(encoding="utf-8"))
        yield from payload
        return
    with path.open(encoding="utf-8", newline="") as handle:
        yield from csv.DictReader(handle)


def parse_year(value: Any) -> int | None:
    try:
        year = int(str(value).strip())
    except (TypeError, ValueError):
        return None
    return year if 1900 < year < 2100 else None


def generate(dataset: Path, schema_sql: Path) -> str:
    parts: list[str] = []
    add = parts.append

    add("-- =====================================================================")
    add("-- Telugu Riddle -- complete Supabase setup")
    add("--")
    add("-- Generated by backend/scripts/generate_seed_sql.py")
    add("-- Paste into the Supabase SQL Editor and Run.")
    add("--")
    add("-- WARNING: this DROPS the public schema and everything in it.")
    add("-- =====================================================================")
    add("")
    add("BEGIN;")
    add("")
    add("-- ---------------------------------------------------------------")
    add("-- 1. Reset the public schema")
    add("-- ---------------------------------------------------------------")
    add("DROP SCHEMA public CASCADE;")
    add("CREATE SCHEMA public;")
    add("")
    add("-- Restore the default grants Supabase expects on a fresh schema.")
    add("-- Guarded per-role: these roles exist on Supabase but not on a")
    add("-- vanilla PostgreSQL server, where an unconditional GRANT aborts.")
    add("DO $$")
    add("DECLARE r text;")
    add("BEGIN")
    add("  FOREACH r IN ARRAY ARRAY['postgres','anon','authenticated','service_role']")
    add("  LOOP")
    add("    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = r) THEN")
    add("      EXECUTE format('GRANT USAGE ON SCHEMA public TO %I', r);")
    add("    END IF;")
    add("  END LOOP;")
    add("  FOREACH r IN ARRAY ARRAY['postgres','service_role']")
    add("  LOOP")
    add("    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = r) THEN")
    add("      EXECUTE format('GRANT ALL ON SCHEMA public TO %I', r);")
    add("    END IF;")
    add("  END LOOP;")
    add("END $$;")
    add("")
    add("-- ---------------------------------------------------------------")
    add("-- 2. Tables and indexes")
    add("-- ---------------------------------------------------------------")
    add("")

    # Reuse the reviewed DDL verbatim rather than duplicating it here.
    ddl = schema_sql.read_text(encoding="utf-8")
    # pg_trgm lives outside the dropped schema; keep the extension creation
    # but let it resolve to wherever Supabase already installed it.
    add(ddl.strip())
    add("")
    add("-- ---------------------------------------------------------------")
    add("-- 3. Movie data")
    add("-- ---------------------------------------------------------------")
    add("")

    movies: list[tuple] = []
    genres: list[tuple[int, str]] = []
    cast_rows: list[tuple[int, str, int]] = []

    seen: set[tuple[str, int]] = set()
    next_id = 1
    skipped = 0

    for row in read_rows(dataset):
        title = str(row.get("movie_name") or row.get("title") or "").strip()
        year = parse_year(row.get("year"))
        if not title or year is None:
            skipped += 1
            continue

        normalized = normalize_title(title)
        key = (normalized, year)
        if key in seen:
            skipped += 1
            continue
        seen.add(key)

        movie_genres = split_values(row.get("genre") or row.get("genres"))
        movie_cast = split_values(row.get("cast"))
        directors = split_values(row.get("director") or row.get("directors"))
        houses = split_values(row.get("production_house"))
        music = split_values(row.get("music_director"))
        writers = split_values(row.get("writer") or row.get("writers"))

        score = quality_score(
            year=year,
            genres=movie_genres,
            cast=movie_cast,
            director=join_values(directors),
            production_house=join_values(houses),
            music_director=join_values(music),
            writer=join_values(writers),
        )
        eligible = is_eligible(
            year=year,
            genres=movie_genres,
            cast=movie_cast,
            director=join_values(directors),
            score=score,
        )

        movie_id = next_id
        next_id += 1

        movies.append(
            (
                movie_id,
                title,
                normalized,
                year,
                str(row.get("language") or "Telugu").strip() or "Telugu",
                join_values(directors),
                join_values(houses),
                join_values(music),
                join_values(writers),
                str(row.get("wikipedia_url") or "").strip() or None,
                score,
                eligible,
            )
        )
        genres.extend((movie_id, genre) for genre in movie_genres)
        # Billing order preserved -- the game surfaces cast position.
        cast_rows.extend(
            (movie_id, actor, position)
            for position, actor in enumerate(movie_cast, start=1)
        )

    # -- movies -------------------------------------------------------
    add(f"-- {len(movies)} movies")
    for start in range(0, len(movies), BATCH):
        chunk = movies[start : start + BATCH]
        add(
            "INSERT INTO movies (id, title, normalized_title, year, language, "
            "director, production_house, music_director, writer, wikipedia_url, "
            "quality_score, is_eligible) VALUES"
        )
        values = [
            "  ({}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {})".format(
                mid,
                quote(title),
                quote(norm),
                year,
                quote(language),
                quote(director),
                quote(house),
                quote(music),
                quote(writer),
                quote(url),
                score,
                "TRUE" if eligible else "FALSE",
            )
            for (mid, title, norm, year, language, director, house, music,
                 writer, url, score, eligible) in chunk
        ]
        add(",\n".join(values) + ";")
        add("")

    # -- genres -------------------------------------------------------
    add(f"-- {len(genres)} genre rows")
    for start in range(0, len(genres), BATCH * 3):
        chunk = genres[start : start + BATCH * 3]
        add("INSERT INTO movie_genres (movie_id, genre) VALUES")
        add(
            ",\n".join(f"  ({mid}, {quote(genre)})" for mid, genre in chunk) + ";"
        )
        add("")

    # -- cast ---------------------------------------------------------
    add(f"-- {len(cast_rows)} cast rows")
    for start in range(0, len(cast_rows), BATCH * 3):
        chunk = cast_rows[start : start + BATCH * 3]
        add("INSERT INTO movie_cast (movie_id, actor_name, cast_position) VALUES")
        add(
            ",\n".join(
                f"  ({mid}, {quote(actor)}, {position})"
                for mid, actor, position in chunk
            )
            + ";"
        )
        add("")

    # Explicit ids were supplied, so the SERIAL sequence must be advanced or
    # the first application insert would collide with id 1.
    add("-- Advance the id sequence past the seeded rows")
    add("SELECT setval('movies_id_seq', (SELECT MAX(id) FROM movies));")
    add("")
    add("COMMIT;")
    add("")
    add("-- ---------------------------------------------------------------")
    add("-- 4. Verify")
    add("-- ---------------------------------------------------------------")
    add("SELECT")
    add("  (SELECT count(*) FROM movies)       AS movies,")
    add("  (SELECT count(*) FROM movie_genres) AS genres,")
    add("  (SELECT count(*) FROM movie_cast)   AS cast_rows,")
    add("  (SELECT count(*) FROM movies WHERE is_eligible) AS eligible;")
    add(f"-- Expect: {len(movies)} | {len(genres)} | {len(cast_rows)} | "
        f"{sum(1 for m in movies if m[11])}")
    add("")

    print(
        f"movies={len(movies)} genres={len(genres)} cast={len(cast_rows)} "
        f"eligible={sum(1 for m in movies if m[11])} skipped={skipped}"
    )
    return "\n".join(parts)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    root = Path(__file__).resolve().parents[2]
    parser.add_argument(
        "--file", type=Path, default=root / "output" / "telugu_movies_2000_2023.csv"
    )
    parser.add_argument("--out", type=Path, default=root / "supabase_setup.sql")
    parser.add_argument(
        "--schema",
        type=Path,
        default=Path(__file__).resolve().parents[1] / "sql" / "schema.sql",
    )
    args = parser.parse_args()

    if not args.file.exists():
        print(f"Dataset not found: {args.file}", file=sys.stderr)
        return 1

    sql = generate(args.file, args.schema)
    args.out.write_text(sql, encoding="utf-8")
    size_mb = args.out.stat().st_size / 1_048_576
    print(f"Wrote {args.out} ({size_mb:.1f} MB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
